// src/components/paiements/PaiementsTable.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { History, Edit, Trash2, Plus, CreditCard, Users, MoreVertical, Wallet, X, Check } from 'lucide-react';
import { useTheme } from '../../contexts/ThemeContext';
import { formatMoney } from '../../lib/formatMoney';

interface Paiement { id: number; employe_id: number; employe_nom: string; employe_prenom: string; employe_poste: string; mois: number; annee: number; montant: number; mode_paiement: string; date_paiement: string; reference?: string; observation?: string; }
interface PaiementsTableProps { paiements: Paiement[]; moisLabels: string[]; onViewHistorique: (employeId: number) => void; onEdit: (paiement: Paiement) => void; onDelete: (id: number) => void; onAdd: () => void; selectedIds?: Set<number>; onSelectAll?: (checked: boolean) => void; onSelectOne?: (id: number, checked: boolean) => void; onBulkDelete?: (ids: number[]) => void; }

const COLORS = { light: { card: '#FFFFFF', surface: '#FFFFFF', surfaceSoft: '#F8FAFC', surfaceMuted: '#F1F5F9', border: '#E2E8F0', text: '#0F172A', muted: '#64748B', subtle: '#94A3B8', primary: '#4F46E5', primaryHover: '#4338CA', primaryBg: 'rgba(79,70,229,0.07)', primaryBorder: 'rgba(79,70,229,0.16)', success: '#059669', successBg: 'rgba(5,150,105,0.07)', danger: '#DC2626', dangerBg: 'rgba(220,38,38,0.07)' }, dark: { card: '#111C30', surface: '#111C30', surfaceSoft: '#0F172A', surfaceMuted: '#162033', border: 'rgba(148,163,184,0.12)', text: '#F8FAFC', muted: '#94A3B8', subtle: '#64748B', primary: '#818CF8', primaryHover: '#6366F1', primaryBg: 'rgba(129,140,248,0.10)', primaryBorder: 'rgba(129,140,248,0.20)', success: '#34D399', successBg: 'rgba(52,211,153,0.10)', danger: '#F87171', dangerBg: 'rgba(248,113,113,0.10)' } };

const safeNumber = (value: unknown, fallback = 0): number => { const number = Number(value); return Number.isFinite(number) ? number : fallback; };
const formatDate = (value?: string): string => { if (!value) return '-'; const date = new Date(value); if (Number.isNaN(date.getTime())) return '-'; return date.toLocaleDateString('fr-FR'); };
const getEmployeeName = (paiement: Paiement): string => { const firstName = paiement.employe_prenom?.trim() || ''; const lastName = paiement.employe_nom?.trim() || ''; const fullName = `${firstName} ${lastName}`.trim(); return fullName || 'Employé inconnu'; };
const getMonthLabel = (mois: number, annee: number, moisLabels: string[]): string => { const monthIndex = safeNumber(mois) - 1; const label = monthIndex >= 0 && monthIndex < moisLabels.length ? moisLabels[monthIndex] : `Mois ${safeNumber(mois) || '-'}`; return `${label} ${safeNumber(annee) || '-'}`; };

const PaiementsTable: React.FC<PaiementsTableProps> = ({ paiements = [], moisLabels = [], onViewHistorique, onEdit, onDelete, onAdd, selectedIds = new Set<number>(), onSelectAll, onSelectOne, onBulkDelete }) => {
  const { isDark } = useTheme(); const theme = isDark ? COLORS.dark : COLORS.light;
  const [openMenuId, setOpenMenuId] = useState<number | null>(null); const [menuPosition, setMenuPosition] = useState<{ top?: number; bottom?: number; left?: number; right?: number; }>({}); const menuRef = useRef<HTMLDivElement | null>(null);
  const calculateMenuPosition = useCallback((button: HTMLButtonElement) => { const rect = button.getBoundingClientRect(); const MENU_WIDTH = 205, MENU_HEIGHT = 52, PADDING = 12, GAP = 5; const viewportWidth = window.innerWidth, viewportHeight = window.innerHeight; const position: { top?: number; bottom?: number; left?: number; right?: number; } = {}; const spaceBelow = viewportHeight - rect.bottom, spaceAbove = rect.top; if (spaceBelow < MENU_HEIGHT + PADDING && spaceAbove >= MENU_HEIGHT + PADDING) position.bottom = viewportHeight - rect.top + GAP; else position.top = rect.bottom + GAP; const idealLeft = rect.right - MENU_WIDTH; position.left = idealLeft >= PADDING ? idealLeft : PADDING; if (position.left !== undefined && position.left + MENU_WIDTH > viewportWidth - PADDING) position.left = viewportWidth - MENU_WIDTH - PADDING; return position; }, []);
  const toggleMenu = useCallback((id: number, event: React.MouseEvent<HTMLButtonElement>) => { event.preventDefault(); event.stopPropagation(); if (openMenuId === id) { setOpenMenuId(null); return; } setMenuPosition(calculateMenuPosition(event.currentTarget)); setOpenMenuId(id); }, [calculateMenuPosition, openMenuId]);
  useEffect(() => { if (openMenuId === null) return; const handleMouseDown = (event: MouseEvent) => { const target = event.target as Node; if (menuRef.current && !menuRef.current.contains(target)) setOpenMenuId(null); }; const handleKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); setOpenMenuId(null); } }; const handleScroll = () => setOpenMenuId(null); document.addEventListener('mousedown', handleMouseDown); document.addEventListener('keydown', handleKeyDown); window.addEventListener('scroll', handleScroll, true); return () => { document.removeEventListener('mousedown', handleMouseDown); document.removeEventListener('keydown', handleKeyDown); window.removeEventListener('scroll', handleScroll, true); }; }, [openMenuId]);
  const handleMenuAction = useCallback((callback: () => void, event: React.MouseEvent) => { event.preventDefault(); event.stopPropagation(); setOpenMenuId(null); callback(); }, []);
  const stats = useMemo(() => { const total = paiements.length; const totalMontant = paiements.reduce((sum, paiement) => sum + safeNumber(paiement.montant), 0); const employesUniques = new Set(paiements.map((paiement) => paiement.employe_id).filter((id) => id !== null && id !== undefined && Number(id) > 0)).size; return { total, totalMontant, employesUniques }; }, [paiements]);
  const allSelected = paiements.length > 0 && paiements.every((paiement) => selectedIds.has(paiement.id)); const someSelected = paiements.some((paiement) => selectedIds.has(paiement.id)) && !allSelected;
  const currentPaiement = openMenuId !== null ? paiements.find((paiement) => paiement.id === openMenuId) : null;

  if (paiements.length === 0) return (<div className="overflow-hidden rounded-xl border shadow-sm" style={{ background: theme.card, borderColor: theme.border }}><div className="flex min-h-[360px] flex-col items-center justify-center px-6 py-12 text-center"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl" style={{ background: theme.primaryBg, color: theme.primary }}><CreditCard size={30} strokeWidth={1.8} /></div><h3 className="text-[16px] font-semibold" style={{ color: theme.text }}>Aucun paiement</h3><p className="mt-1.5 max-w-md text-[13px] leading-5" style={{ color: theme.muted }}>Ajoutez un paiement pour commencer à suivre les rémunérations.</p><button type="button" onClick={onAdd} className="mt-6 flex h-9 items-center gap-2 rounded-lg px-4 text-[13px] font-semibold text-white shadow-sm transition-all duration-150 hover:shadow-md active:scale-[0.98]" style={{ background: theme.primary }} onMouseEnter={(event) => { event.currentTarget.style.background = theme.primaryHover; }} onMouseLeave={(event) => { event.currentTarget.style.background = theme.primary; }}><Plus size={15} />Ajouter un paiement</button></div></div>);

  return (<div className="relative overflow-hidden rounded-xl border shadow-sm" style={{ background: theme.card, borderColor: theme.border }}>
    {selectedIds.size > 0 && (<div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-2.5" style={{ background: isDark ? '#0F172A' : '#EEF2FF', borderColor: theme.border }}><div className="flex items-center gap-2"><div className="flex h-6 w-6 items-center justify-center rounded-md" style={{ background: theme.primaryBg, color: theme.primary }}><Check size={14} /></div><span className="text-[13px] font-semibold" style={{ color: isDark ? '#E2E8F0' : '#4338CA' }}>{selectedIds.size} paiement{selectedIds.size > 1 ? 's' : ''} sélectionné{selectedIds.size > 1 ? 's' : ''}</span></div><div className="flex items-center gap-2"><button type="button" onClick={() => onBulkDelete?.(Array.from(selectedIds))} className="flex h-8 items-center gap-1.5 rounded-md px-3 text-[12px] font-semibold text-white transition-all duration-150 hover:shadow-sm active:scale-[0.98]" style={{ background: '#DC2626' }}><Trash2 size={14} />Supprimer</button><button type="button" onClick={() => onSelectAll?.(false)} className="flex h-8 items-center gap-1.5 rounded-md border px-3 text-[12px] font-medium transition-all duration-150 active:scale-[0.98]" style={{ background: theme.surface, borderColor: theme.border, color: theme.text }}><X size={14} />Désélectionner</button></div></div>)}
    <div className="custom-paiements-scrollbar overflow-x-auto">
      {/* ⭐ BORDER SEPARATE + SPACING 0 -> Mitovy amin'ny tabilao hafa */}
      <table className="w-full min-w-[950px] border-separate border-spacing-0 text-left" style={{ borderColor: theme.border }}>
        <thead style={{ background: theme.surface }}>
          <tr>
            <th className="w-[42px] border px-3 py-2" style={{ borderColor: theme.border }}><input type="checkbox" checked={allSelected} ref={(element) => { if (element) element.indeterminate = someSelected; }} onChange={(event) => onSelectAll?.(event.target.checked)} aria-label="Sélectionner tous les paiements" className="h-4 w-4 cursor-pointer rounded border-slate-300 text-indigo-600 focus:ring-indigo-500 dark:border-slate-600" /></th>
            <th className="w-[210px] border px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.06em]" style={{ color: theme.subtle, borderColor: theme.border }}>Employé</th>
            <th className="w-[145px] border px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.06em]" style={{ color: theme.subtle, borderColor: theme.border }}>Période</th>
            <th className="w-[145px] border px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.06em]" style={{ color: theme.subtle, borderColor: theme.border }}>Montant</th>
            <th className="w-[130px] border px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.06em]" style={{ color: theme.subtle, borderColor: theme.border }}>Mode</th>
            <th className="w-[120px] border px-3 py-2 text-[11px] font-semibold uppercase tracking-[0.06em]" style={{ color: theme.subtle, borderColor: theme.border }}>Date</th>
            <th className="w-[105px] border px-3 py-2 text-right text-[11px] font-semibold uppercase tracking-[0.06em]" style={{ color: theme.subtle, borderColor: theme.border }}>Actions</th>
          </tr>
        </thead>
        <tbody style={{ background: theme.surface }}>
          {paiements.map((paiement) => {
            const isSelected = selectedIds.has(paiement.id); const montant = safeNumber(paiement.montant); const employeeName = getEmployeeName(paiement); const periode = getMonthLabel(paiement.mois, paiement.annee, moisLabels);
            return (<tr key={paiement.id} className="group h-[54px] transition-colors duration-150" style={{ background: isSelected ? (isDark ? 'rgba(99,102,241,0.10)' : '#EEF2FF') : theme.surface }} onMouseEnter={(event) => { if (!isSelected) { event.currentTarget.style.background = isDark ? 'rgba(30,41,59,0.55)' : '#F8FAFC'; } }} onMouseLeave={(event) => { if (!isSelected) { event.currentTarget.style.background = theme.surface; } }}>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }} onClick={(event) => event.stopPropagation()}><input type="checkbox" checked={isSelected} onChange={(event) => onSelectOne?.(paiement.id, event.target.checked)} aria-label={`Sélectionner le paiement ${paiement.id}`} className="h-4 w-4 cursor-pointer rounded border-slate-300 text-indigo-600 focus:ring-indigo-500 dark:border-slate-600" /></td>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }}><div className="min-w-0"><div className="truncate text-[13px] font-semibold transition-colors" style={{ color: theme.text }}>{employeeName}</div><div className="mt-0.5 truncate text-[11px]" style={{ color: theme.muted }}>{paiement.employe_poste || 'Poste non spécifié'}</div></div></td>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }}><span className="text-[13px] font-medium" style={{ color: theme.text }}>{periode}</span></td>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }}><span className="text-[13px] font-bold" style={{ color: theme.success }}>{formatMoney(montant)}</span></td>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }}><span className="inline-flex max-w-[110px] truncate rounded-md border px-2 py-1 text-[11px] font-semibold" style={{ background: theme.primaryBg, borderColor: theme.primaryBorder, color: theme.primary }}>{paiement.mode_paiement || 'Non spécifié'}</span></td>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }}><span className="text-[12px]" style={{ color: theme.muted }}>{formatDate(paiement.date_paiement)}</span></td>
              <td className="border px-3 py-2 align-middle" style={{ borderColor: theme.border }} onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-end gap-0.5"><button type="button" onClick={() => onViewHistorique(paiement.employe_id)} title="Voir l'historique" aria-label="Voir l'historique" className="flex h-7 w-7 items-center justify-center rounded-md opacity-0 transition-all duration-150 group-hover:opacity-100 focus:opacity-100" style={{ color: theme.subtle }} onMouseEnter={(event) => { event.currentTarget.style.background = theme.primaryBg; event.currentTarget.style.color = theme.primary; }} onMouseLeave={(event) => { event.currentTarget.style.background = 'transparent'; event.currentTarget.style.color = theme.subtle; }}><History size={15} /></button><button type="button" onClick={() => onEdit(paiement)} title="Modifier" aria-label="Modifier" className="flex h-7 w-7 items-center justify-center rounded-md opacity-0 transition-all duration-150 group-hover:opacity-100 focus:opacity-100" style={{ color: theme.subtle }} onMouseEnter={(event) => { event.currentTarget.style.background = theme.primaryBg; event.currentTarget.style.color = theme.primary; }} onMouseLeave={(event) => { event.currentTarget.style.background = 'transparent'; event.currentTarget.style.color = theme.subtle; }}><Edit size={15} /></button><button type="button" onClick={(event) => toggleMenu(paiement.id, event)} title="Plus d'actions" aria-label="Plus d'actions" aria-expanded={openMenuId === paiement.id} className="flex h-7 w-7 items-center justify-center rounded-md transition-all duration-150" style={{ color: theme.muted }} onMouseEnter={(event) => { event.currentTarget.style.background = isDark ? 'rgba(255,255,255,0.06)' : '#F1F5F9'; event.currentTarget.style.color = theme.text; }} onMouseLeave={(event) => { event.currentTarget.style.background = 'transparent'; event.currentTarget.style.color = theme.muted; }}><MoreVertical size={17} /></button></div></td>
            </tr>);
          })}
        </tbody>
      </table>
    </div>
    {openMenuId !== null && currentPaiement && createPortal(<div ref={menuRef} className="fixed z-[99999] w-[205px] overflow-hidden rounded-xl border py-1.5 shadow-2xl" style={{ ...menuPosition, background: theme.card, borderColor: theme.border, boxShadow: isDark ? '0 20px 60px rgba(0,0,0,0.45)' : '0 20px 60px rgba(15,23,42,0.18)' }} onMouseDown={(event) => event.stopPropagation()}>
      <div className="border-b px-3 py-2" style={{ borderColor: theme.border }}><div className="truncate text-[11px] font-semibold" style={{ color: theme.text }}>{getEmployeeName(currentPaiement)}</div><div className="mt-0.5 text-[10px]" style={{ color: theme.subtle }}>{getMonthLabel(currentPaiement.mois, currentPaiement.annee, moisLabels)}</div></div>
      <button type="button" onMouseDown={(event) => handleMenuAction(() => onDelete(currentPaiement.id), event)} className="flex w-full items-center px-3.5 py-2.5 text-left text-[12px] font-medium transition-colors" style={{ color: theme.danger }} onMouseEnter={(event) => { event.currentTarget.style.background = theme.dangerBg; }} onMouseLeave={(event) => { event.currentTarget.style.background = 'transparent'; }}><Trash2 size={15} className="mr-2.5 shrink-0" /><span>Supprimer le paiement</span></button>
    </div>, document.body)}
    <div className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-3" style={{ background: theme.surfaceSoft, borderColor: theme.border }}>
      <div className="flex flex-wrap items-center gap-4 text-[12px]" style={{ color: theme.muted }}>
        <span className="flex items-center gap-1.5"><CreditCard size={14} style={{ color: theme.primary }} /><span><strong className="font-semibold" style={{ color: theme.text }}>{stats.total}</strong> paiement{stats.total > 1 ? 's' : ''}</span></span>
        <span className="hidden h-4 w-px sm:block" style={{ background: theme.border }} />
        <span className="flex items-center gap-1.5"><Wallet size={14} style={{ color: theme.success }} /><span className="font-semibold" style={{ color: theme.text }}>{formatMoney(stats.totalMontant)}</span></span>
        <span className="hidden h-4 w-px sm:block" style={{ background: theme.border }} />
        <span className="flex items-center gap-1.5"><Users size={14} style={{ color: theme.primary }} /><span><strong className="font-semibold" style={{ color: theme.text }}>{stats.employesUniques}</strong> employé{stats.employesUniques > 1 ? 's' : ''}</span></span>
      </div>
      {selectedIds.size > 0 && (<div className="rounded-md border px-2.5 py-1 text-[11px] font-medium" style={{ color: theme.primary, background: theme.primaryBg, borderColor: theme.primaryBorder }}>{selectedIds.size} sélectionné{selectedIds.size > 1 ? 's' : ''}</div>)}
    </div>
    <style>{`.custom-paiements-scrollbar::-webkit-scrollbar { width: 6px; height: 6px; } .custom-paiements-scrollbar::-webkit-scrollbar-track { background: transparent; } .custom-paiements-scrollbar::-webkit-scrollbar-thumb { background: rgba(100, 116, 139, 0.30); border-radius: 999px; } .custom-paiements-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(100, 116, 139, 0.50); } .custom-paiements-scrollbar { scrollbar-width: thin; scrollbar-color: rgba(100, 116, 139, 0.30) transparent; }`}</style>
  </div>);
};
export default PaiementsTable;