import React, { useEffect } from 'react';
import { Receipt, X, DollarSign, Calendar as CalendarIcon, History, Briefcase, Wallet, Hash, FileText } from 'lucide-react';
import { useTheme } from '../../contexts/ThemeContext';
import { formatMoney } from '../../lib/formatMoney';

interface Paiement { id: number; employe_id: number; employe_nom: string; employe_prenom: string; employe_poste: string; mois: number; annee: number; montant: number; mode_paiement: string; date_paiement: string; reference?: string; observation?: string; created_at: string; }
interface PaiementsViewModalProps { paiement: Paiement; moisLabels: string[]; onClose: () => void; onViewHistorique: () => void; }

const PaiementsViewModal: React.FC<PaiementsViewModalProps> = ({ paiement, moisLabels, onClose, onViewHistorique }) => {
  const { isDark } = useTheme();
  useEffect(() => { const handleKeyDown = (e: KeyboardEvent) => { if (e.key === 'Escape') { e.preventDefault(); onClose(); } }; window.addEventListener('keydown', handleKeyDown); return () => window.removeEventListener('keydown', handleKeyDown); }, [onClose]);
  const borderColor = isDark ? 'border-white/[0.055]' : 'border-slate-200';
  const formatDateTime = (value?: string) => { if (!value) return '—'; const date = new Date(value); if (Number.isNaN(date.getTime())) return '—'; return date.toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }); };
  const periode = moisLabels[paiement.mois - 1] || `Mois ${paiement.mois}`;

  return (<div className="fixed inset-0 z-[99990] flex items-center justify-center bg-black/50 dark:bg-black/75 p-4 sm:p-6 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}>
    <div className={`relative flex w-full max-w-2xl max-h-[90vh] flex-col overflow-hidden rounded-2xl border bg-white dark:bg-[#111c30] shadow-[0_24px_70px_rgba(0,0,0,0.28)] ${borderColor} animate-[paiementModalIn_180ms_ease-out]`} onMouseDown={(e) => e.stopPropagation()}>
      <div className={`flex shrink-0 items-center justify-between border-b px-5 py-4 ${borderColor}`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10 dark:text-indigo-400"><Receipt size={19} strokeWidth={2} /></div><div><h2 className="text-[16px] font-semibold text-slate-900 dark:text-slate-100">Détails du paiement</h2><p className="mt-0.5 text-[12px] text-slate-500 dark:text-slate-400">Informations détaillées de la rémunération</p></div></div><button type="button" onClick={onClose} aria-label="Fermer" className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800 dark:hover:text-slate-200"><X size={18} /></button></div>
      <div className="custom-modal-scrollbar flex-1 overflow-y-auto p-5"><div className="space-y-4">
        <div className={`rounded-xl border p-4 bg-indigo-50/70 dark:bg-indigo-500/[0.08] ${borderColor}`}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-indigo-100 text-indigo-600 dark:bg-indigo-500/10 dark:text-indigo-400"><Briefcase size={18} /></div><div className="min-w-0"><p className="text-[12px] font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">Employé</p><p className="mt-1 truncate text-[17px] font-semibold text-slate-900 dark:text-slate-100">{paiement.employe_prenom} {paiement.employe_nom}</p><p className="mt-1 flex items-center gap-1.5 text-[13px] text-slate-500 dark:text-slate-400"><Briefcase size={13} />{paiement.employe_poste || 'Poste non renseigné'}</p></div></div></div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div className={`rounded-xl border p-4 bg-slate-50 dark:bg-[#0F172A] ${borderColor}`}><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Période</p><div className="mt-2 flex items-center gap-2"><CalendarIcon size={16} className="text-indigo-500 dark:text-indigo-400" /><span className="text-[14px] font-semibold capitalize text-slate-900 dark:text-slate-100">{periode} {paiement.annee}</span></div></div><div className={`rounded-xl border p-4 bg-emerald-50/60 dark:bg-emerald-500/[0.07] ${borderColor}`}><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Montant</p><div className="mt-2 flex items-center gap-2"><DollarSign size={17} className="text-emerald-600 dark:text-emerald-400" /><span className="text-[18px] font-bold text-emerald-600 dark:text-emerald-400">{formatMoney(paiement.montant)}</span></div></div><div className={`rounded-xl border p-4 bg-slate-50 dark:bg-[#0F172A] ${borderColor}`}><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Mode de paiement</p><div className="mt-2 flex items-center gap-2"><Wallet size={16} className="text-indigo-500 dark:text-indigo-400" /><span className="inline-flex rounded-md bg-indigo-50 px-2.5 py-1 text-[13px] font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300">{paiement.mode_paiement || '—'}</span></div></div><div className={`rounded-xl border p-4 bg-slate-50 dark:bg-[#0F172A] ${borderColor}`}><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Date de paiement</p><div className="mt-2 flex items-center gap-2"><CalendarIcon size={16} className="text-slate-400 dark:text-slate-500" /><span className="text-[13px] font-medium text-slate-900 dark:text-slate-100">{formatDateTime(paiement.date_paiement)}</span></div></div>{paiement.reference && <div className={`rounded-xl border p-4 bg-slate-50 dark:bg-[#0F172A] ${borderColor}`}><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Référence</p><div className="mt-2 flex items-center gap-2"><Hash size={16} className="text-slate-400 dark:text-slate-500" /><span className="truncate text-[13px] font-medium text-slate-900 dark:text-slate-100">{paiement.reference}</span></div></div>}<div className={`rounded-xl border p-4 bg-slate-50 dark:bg-[#0F172A] ${borderColor}`}><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Créé le</p><div className="mt-2 flex items-center gap-2"><CalendarIcon size={16} className="text-slate-400 dark:text-slate-500" /><span className="text-[13px] font-medium text-slate-900 dark:text-slate-100">{formatDateTime(paiement.created_at)}</span></div></div></div>
        {paiement.observation && <div className={`rounded-xl border p-4 bg-slate-50 dark:bg-[#0F172A] ${borderColor}`}><div className="flex items-center gap-2"><FileText size={15} className="text-indigo-500 dark:text-indigo-400" /><p className="text-[12px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Observation</p></div><p className="mt-2 whitespace-pre-wrap text-[14px] leading-6 text-slate-700 dark:text-slate-300">{paiement.observation}</p></div>}
      </div></div>
      <div className={`flex shrink-0 flex-col-reverse gap-2 border-t px-5 py-3 sm:flex-row sm:items-center sm:justify-end ${borderColor}`}><button type="button" onClick={onClose} className="h-9 rounded-lg px-4 text-[14px] font-medium text-slate-600 transition-colors hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Fermer</button><button type="button" onClick={onViewHistorique} className="flex h-9 items-center justify-center gap-1.5 rounded-lg bg-emerald-600 px-4 text-[14px] font-medium text-white shadow-sm transition-all hover:bg-emerald-700 hover:shadow-md active:scale-[0.98]"><History size={15} />Voir historique</button></div>
    </div>
    <style>{`@keyframes paiementModalIn { from { opacity: 0; transform: translateY(8px) scale(0.985); } to { opacity: 1; transform: translateY(0) scale(1); } } .custom-modal-scrollbar::-webkit-scrollbar { width: 6px; } .custom-modal-scrollbar::-webkit-scrollbar-track { background: transparent; } .custom-modal-scrollbar::-webkit-scrollbar-thumb { background: rgba(100, 116, 139, 0.28); border-radius: 999px; } .custom-modal-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(100, 116, 139, 0.45); }`}</style>
  </div>);
};
export default PaiementsViewModal;