// src/components/mouvements/MouvementsSearchBar.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Search, X, Grid, List, ArrowUpDown, Filter, RotateCcw } from 'lucide-react';
import { useTheme } from '../../contexts/ThemeContext';

const SORT_OPTIONS = [{ value: 'Date (Récent)', label: 'Date récent' }, { value: 'Date (Ancien)', label: 'Date ancien' }, { value: 'Quantité (Croissant)', label: 'Quantité ↑' }, { value: 'Quantité (Décroissant)', label: 'Quantité ↓' }];
const TYPE_OPTIONS = [{ value: '', label: 'Tous les mouvements' }, { value: 'ENTREE', label: 'Entrées' }, { value: 'SORTIE', label: 'Sorties' }, { value: 'AJUSTEMENT', label: 'Ajustements' }];

interface MouvementsSearchBarProps { searchTerm: string; onSearchChange: (value: string) => void; filterType: string; onFilterTypeChange: (value: string) => void; sortOption: string; onSortChange: (value: string) => void; viewMode: 'table' | 'grid'; onViewModeChange: (mode: 'table' | 'grid') => void; isLoading?: boolean; }

const MouvementsSearchBar: React.FC<MouvementsSearchBarProps> = ({ searchTerm, onSearchChange, filterType, onFilterTypeChange, sortOption, onSortChange, viewMode, onViewModeChange, isLoading = false }) => {
  const { isDark } = useTheme();
  const [localSearch, setLocalSearch] = useState(searchTerm);
  const [isFocused, setIsFocused] = useState(false);
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const controlBorder = isDark ? 'border-white/[0.08]' : 'border-slate-300';
  const controlHoverBorder = isDark ? 'hover:border-slate-600' : 'hover:border-slate-400';
  const controlBackground = isDark ? 'bg-[#0F172A]' : 'bg-white';
  const controlText = isDark ? 'text-slate-200' : 'text-slate-700';
  const controlShadow = isDark ? 'shadow-[0_1px_2px_rgba(0,0,0,0.12)]' : 'shadow-[0_1px_2px_rgba(15,23,42,0.05)]';

  useEffect(() => { setLocalSearch(searchTerm); }, [searchTerm]);
  const handleSearchChange = useCallback((value: string) => { setLocalSearch(value); if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current); debounceTimerRef.current = setTimeout(() => { onSearchChange(value); }, 300); }, [onSearchChange]);
  useEffect(() => { return () => { if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current); }; }, []);
  const hasActiveFilters = localSearch.trim() !== '' || filterType !== '';
  const handleReset = () => { if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current); setLocalSearch(''); onSearchChange(''); onFilterTypeChange(''); onSortChange('Date (Récent)'); };

  if (isLoading) return (<div className="mb-4 w-full animate-pulse"><div className="flex flex-col gap-2.5 xl:flex-row xl:items-center"><div className={`h-10 min-w-[260px] flex-1 rounded-lg border ${isDark ? 'border-white/[0.05] bg-slate-800' : 'border-slate-300 bg-slate-200'}`} /><div className="flex items-center gap-2.5"><div className={`h-10 w-[165px] rounded-lg border ${isDark ? 'border-white/[0.05] bg-slate-800' : 'border-slate-300 bg-slate-200'}`} /><div className={`h-10 w-[150px] rounded-lg border ${isDark ? 'border-white/[0.05] bg-slate-800' : 'border-slate-300 bg-slate-200'}`} /><div className={`h-10 w-[150px] rounded-lg border ${isDark ? 'border-white/[0.05] bg-slate-800' : 'border-slate-300 bg-slate-200'}`} /></div></div></div>);

  return (<div className="mb-4 w-full"><div className="flex flex-col gap-2.5 xl:flex-row xl:items-center">
    <div className="relative min-w-0 flex-1"><Search size={18} strokeWidth={2} className={`pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 transition-colors duration-150 ${isFocused ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-400 dark:text-slate-500'}`} /><input type="text" placeholder="Rechercher un mouvement..." value={localSearch} onChange={(e) => handleSearchChange(e.target.value)} onFocus={() => setIsFocused(true)} onBlur={() => setIsFocused(false)} className={`h-10 w-full rounded-lg border ${controlBorder} ${controlBackground} pl-11 pr-10 text-sm font-medium ${controlText} outline-none placeholder:text-slate-400 dark:placeholder:text-slate-500 ${controlShadow} transition-all duration-150 ${controlHoverBorder} ${isFocused ? 'border-indigo-500 ring-2 ring-indigo-500/10' : ''}`} />{localSearch && (<button type="button" onClick={() => handleSearchChange('')} className="absolute right-2.5 top-1/2 -translate-y-1/2 rounded-md p-1 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800 dark:hover:text-slate-200" aria-label="Effacer la recherche"><X size={15} /></button>)}</div>
    <div className="flex shrink-0 items-center gap-2.5 overflow-x-auto pb-0.5">
      <div className="relative shrink-0"><Filter size={14} strokeWidth={2} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 dark:text-slate-500" /><select value={filterType} onChange={(e) => onFilterTypeChange(e.target.value)} className={`h-10 w-[170px] cursor-pointer appearance-none rounded-lg border ${controlBorder} ${controlBackground} pl-9 pr-8 text-sm font-medium ${controlText} outline-none ${controlShadow} transition-all ${controlHoverBorder} hover:bg-slate-50 dark:hover:bg-slate-800/60 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10`}>{TYPE_OPTIONS.map((option) => (<option key={option.value} value={option.value}>{option.label}</option>))}</select></div>
      <div className="relative shrink-0"><ArrowUpDown size={14} strokeWidth={2} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 dark:text-slate-500" /><select value={sortOption} onChange={(e) => onSortChange(e.target.value)} className={`h-10 w-[155px] cursor-pointer appearance-none rounded-lg border ${controlBorder} ${controlBackground} pl-9 pr-8 text-sm font-medium ${controlText} outline-none ${controlShadow} transition-all ${controlHoverBorder} hover:bg-slate-50 dark:hover:bg-slate-800/60 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/10`}>{SORT_OPTIONS.map((option) => (<option key={option.value} value={option.value}>{option.label}</option>))}</select></div>
      <div className={`flex h-10 shrink-0 items-center rounded-lg border ${controlBorder} ${controlBackground} p-0.5 ${controlShadow}`} role="group" aria-label="Mode d'affichage"><button type="button" onClick={() => onViewModeChange('table')} className={`flex h-9 items-center gap-1.5 rounded-md px-3 text-xs font-semibold transition-all ${viewMode === 'table' ? 'bg-indigo-50 text-indigo-700 shadow-sm dark:bg-indigo-500/10 dark:text-indigo-300' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-700 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-slate-200'}`} title="Vue tableau"><List size={15} strokeWidth={2} /><span>Table</span></button><button type="button" onClick={() => onViewModeChange('grid')} className={`flex h-9 items-center gap-1.5 rounded-md px-3 text-xs font-semibold transition-all ${viewMode === 'grid' ? 'bg-indigo-50 text-indigo-700 shadow-sm dark:bg-indigo-500/10 dark:text-indigo-300' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-700 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-slate-200'}`} title="Vue grille"><Grid size={15} strokeWidth={2} /><span>Grille</span></button></div>
    </div>
  </div>
  {hasActiveFilters && (<div className="mt-2.5 flex flex-wrap items-center justify-between gap-2 px-0.5"><div className="flex flex-wrap items-center gap-1.5"><span className="mr-1 text-xs font-medium text-slate-400 dark:text-slate-500">Filtres actifs</span>{localSearch.trim() && (<FilterChip icon={<Search size={11} />} label={`"${localSearch.trim()}"`} onRemove={() => handleSearchChange('')} />)}{filterType && (<FilterChip icon={<Filter size={11} />} label={TYPE_OPTIONS.find((type) => type.value === filterType)?.label || filterType} onRemove={() => onFilterTypeChange('')} />)}</div><button type="button" onClick={handleReset} className="inline-flex items-center gap-1.5 rounded-md border border-transparent px-2 py-1 text-xs font-semibold text-slate-500 transition-all hover:border-indigo-100 hover:bg-indigo-50 hover:text-indigo-600 dark:text-slate-400 dark:hover:border-indigo-500/20 dark:hover:bg-indigo-500/10 dark:hover:text-indigo-400"><RotateCcw size={12} />Réinitialiser</button></div>)}
  </div>);
};

const FilterChip: React.FC<{ label: string; icon?: React.ReactNode; onRemove: () => void; }> = ({ label, icon, onRemove }) => {
  return (<span className="inline-flex max-w-[220px] items-center gap-1.5 rounded-md border border-indigo-200 bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 transition-colors dark:border-indigo-500/20 dark:bg-indigo-500/10 dark:text-indigo-300">{icon && <span className="shrink-0 opacity-70">{icon}</span>}<span className="truncate">{label}</span><button type="button" onClick={onRemove} className="shrink-0 rounded p-0.5 text-indigo-400 transition-colors hover:bg-indigo-100 hover:text-indigo-700 dark:hover:bg-indigo-500/20 dark:hover:text-indigo-200" aria-label={`Supprimer le filtre ${label}`}><X size={11} /></button></span>);
};
export default MouvementsSearchBar;